/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { JinGoFundMe } from "./JinGoFundMe";
export * as factories from "./factories";
export { JinGoFundMe__factory } from "./factories/JinGoFundMe__factory";
export { Lock__factory } from "./factories/Lock__factory";
